### ISSUE TITLE
MaryTTS build fails with Plugin included under Ubuntu 18.04

### ISSUE THREAD

**Issue by drjJj** [marytts/gradle-marytts-voicebuilding-plugin#112]
Running "./gradlew build" with the plugin included leads to the following error:

```
FAILURE: Build failed with an exception.

* Where:
Script '/home/aura/marytts/applicationLogic.gradle' line: 1

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin [id 'org.gradle.application']
   > Cannot add task 'run' as a task with that name already exists.
```

"build.gradle" file used:
```groovy
plugins {
    id 'base'
    id 'de.dfki.mary.voicebuilding-legacy' version '5.4'
}

allprojects {
    group 'de.dfki.mary'
    version '6.0-SNAPSHOT'

    repositories {
        jcenter()
    }
}

apply from: 'applicationLogic.gradle'
```
Running "./gradlew build" without the plugin added terminates without errors.

**Comment by psibre** [comment]
I don't understand your use case. The voicebuilding plugin is not intended to be combined with the MaryTTS core in the same project; in fact, the voicebuilding plugin has *dependencies* on `marytts-runtime` etc.

**Comment by JohannesHartz** [comment]
My use case is quite simple, I want to build a voice with MaryTTS. I was able now to compile the plugin standalone, but still lack the understanding how to use it to build a voice. Where can I find some documentation describing the process using the new Gradle-based version of MaryTTS for voice building (v6)? The MaryTTS Wiki still only describes the old way (v5).

**Comment by psibre** [comment]
Please see [the README](https://github.com/marytts/gradle-marytts-voicebuilding-plugin/blob/master/README.md); feel free to suggest updates if you find it inaccurate or incomplete. =)

**Comment by drjJj** [comment]
The documentation is not trying to be helpful for users which are inexperienced with Gradle. The information from here https://github.com/marytts/gradle-marytts-voicebuilding-plugin/issues/95 should be included as well as a short explanation of the correct Gradle project setup. Also the plugin pretty much only works under Gradle 4.10.2 used for the root project, which is also not documented.

**Comment by ucasiggcas** [comment]
have got success ?
pls help me ?
thx
