### ISSUE TITLE
how  to install SoX and Edinburgh Speech Tools  in Android Studio？

### ISSUE THREAD

**Issue by ucasiggcas** [marytts/gradle-marytts-voicebuilding-plugin#114]
hi,
wanna install the two ,but can't find the right web address,
and then how to install in the app ?

any one has got app successfully ?
please help me ,thx

**Comment by seblemaguer** [comment]
Hello,

sox and speech tools are binaries. You have to install them according to your distributions (see the prerequisites section of the README).

**Comment by seblemaguer** [comment]
I close the issue, if more info needed don't hesitate to reopen it
