### ISSUE TITLE
Project layout ?

### ISSUE THREAD

**Issue by ucasiggcas** [marytts/gradle-marytts-voicebuilding-plugin#115]
hi,
how to get the files ?
```
build
├── lab
│   ├── utt0001.lab
│   ├── utt0002.lab
│   ├── utt0003.lab
│   ├── utt0004.lab
│   └── utt0005.lab
├── text
│   ├── utt0001.txt
│   ├── utt0002.txt
│   ├── utt0003.txt
│   ├── utt0004.txt
│   └── utt0005.txt
└── resources
    └── data
        ├── utt0001.wav
        ├── utt0002.wav
        ├── utt0003.wav
        ├── utt0004.wav
        └── utt0005.wav
```

thx

**Comment by muntasir2000** [comment]
I hope you have a speech corpus to train with. The wav and text files will come from that. And you need to apply [https://github.com/marytts/gradle-marytts-kaldi-mfa-plugin](url) to generate the lab files by aligning your wav and text files.

**Comment by seblemaguer** [comment]
hello,

in case of, everything present in build has been produced by the plugin and is not to download from somewhere.
