### ISSUE TITLE
An exception occurred applying plugin request [id: 'de.dfki.mary.voicebuilding-legacy', version: '5.4']

### ISSUE THREAD

**Issue by elnursamedzade** [marytts/gradle-marytts-voicebuilding-plugin#123]
Hello again.
Mr. Psibre, as you said, I downloaded gradle v4.10.3 and added it to the path.
I went to the gradle-marytts-voicebuilding-plugin folder and opened a cmd window by doing shift + rightclick and ran the gradlew build command. However, gradle v6.3 version was still downloaded and later gave the following error again:
```
.........10%..........20%..........30%.........40%..........50%..........60%.........70%..........80%..........90%......
....100%

Welcome to Gradle 6.3!

Here are the highlights of this release:
 - Java 14 support
 - Improved error messages for unexpected failures

For more details see https://docs.gradle.org/6.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Elnur\gradle-marytts-voicebuilding-plugin\build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'de.dfki.mary.voicebuilding-legacy', version: '5.4']
> Failed to apply plugin [class 'de.dfki.mary.voicebuilding.VoicebuildingBasePlugin']
   > Could not create task ':generateSource'.
      > Could not create task of type 'GenerateSource'.
         > Could not find method newOutputDirectory() for arguments [] on task ':generateSource' of type de.dfki.mary.vo
icebuilding.tasks.GenerateSource.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BU¦LD FAILED in 1m 44s

C:\Users\Elnur\gradle-marytts-voicebuilding-plugin>
```

**Comment by psibre** [comment]
@elnursamedzade Fixed formatting for you.

**Comment by psibre** [comment]
The voicebuilding plugin is *applied* to your TTS voice building project. You can either use the published version (currently v5.4), and then you need Gradle 4 or 5 *in your voicebuilding project*.
See https://plugins.gradle.org/plugin/de.dfki.mary.voicebuilding-legacy

Or you want to live on the edge and know how to develop Gradle plugins and are fine with Git submodules -- then you can use the current master.

**Comment by elnursamedzade** [comment]
Hello Psibre.
To date, I have never used gradle and plugins. Because I'm not a java programmer. But I want to synthesize my own voice with marytts. Please send a sample project that you know me and txt files in wav lab? Maybe it can help me understand something. I present my respects.

**Comment by psibre** [comment]
Have a look at how we do it for [marytts/voice-cmu-slt](https://github.com/marytts/voice-cmu-slt) or [marytts/voice-dfki-spike](https://github.com/marytts/voice-dfki-spike). Note that those voice have not yet been updated to use v5.4 of the plugin, but the basic process is pretty much the same.

The relevant documentation is in this project's README.

**Comment by elnursamedzade** [comment]
yes, i tested the related projects.  however, I could not find wav or lab
files in it.  tr turkish project worked for me.  But how can I change my
own voice with the sound there?

**Comment by psibre** [comment]
The actual voice data is not part of those repositories. They contain build logic that downloads and unpacks the data from other sources, as documented in the respective READMEs.

**Comment by psibre** [comment]
> But how can I change myown voice with the sound there?

See https://github.com/marytts/gradle-marytts-voicebuilding-plugin#project-layout

**Comment by elnursamedzade** [comment]
Can you send me the uncompiled version of the tr project to me?  my goal is
to recompile wav files with my own voice.

18 May 2020 Pzt 16:28 tarihinde psibre <notifications@github.com> şunu
yazdı:

**Comment by psibre** [comment]
> Can you send me the uncompiled version of the tr project to me?  my goal is
to recompile wav files with my own voice.

I'm afraid I'm not sure what you mean. Please have a look at the [marytts/voice-dfki-ot](https://github.com/marytts/voice-dfki-ot) project for inspiration how you can provide you own voice data.

This issue is resolved.
