### ISSUE TITLE
reference new allophone set

### ISSUE THREAD

**Issue by ingosiegert** [marytts/gradle-marytts-voicebuilding-plugin#132]
If I want to create a new voice, I also have to specify an allophone set. How do I specify the corresponding file, which I have locally on my computer?

**Comment by seblemaguer** [comment]
You have to create a new language. The voice building plugin assume you have already that available.

**Comment by ingosiegert** [comment]
Oh. OK. Thanks. Then I think I have to somehow make this plugin aware of my marytts installation...
