### ISSUE TITLE
Do tasks open the Swing UI?

### ISSUE THREAD

**Issue by posttool** [marytts/gradle-marytts-voicebuilding-plugin#3]
It seems that many of the tasks open the DatabaseImport UI. Is there are way to bypass? Or tips for getting around?

**Comment by psibre** [comment]
This is a side-effect of running the DatabaseImportMain class in the LegacyVoiceImportTask. The legacy tasks will be replaced by groovy ones, which will make this a non-issue.

**Comment by psibre** [comment]
Better late than never! =)
